# Generated by Django 3.1.3 on 2021-01-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210114_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
